#!/bin/bash
#

#docker run --privileged --net=host \
#       --device=/dev/switchtec0 \
#       --device=/dev/infiniband/rdma_cm \
#       --device=/dev/infiniband/uverbs0 \
#       --device=/dev/infiniband/uverbs1 \
#       --cap-add SYS_PTRACE -it rdma:latest

docker run --ulimit memlock=-1 \
       --device=/dev/switchtec0 \
       --device=/dev/infiniband/rdma_cm \
       --device=/dev/infiniband/uverbs0 \
       --cap-add SYS_PTRACE -it rdma:latest
