#!/bin/bash
#
# A simple bash script to setup a NVMe over Fabrics server. You can
# call this for example with something like:
#
# P2PMEM=yes ./setup-nvmet
#
# This version is for the Xilinx SuperCompute 17 demo and exposes all
# the NoLoad namespaces. It also drops the p2pmem option as this
# is not used in that demo.

set -e

CFG=${CFG:-/sys/kernel/config/}
SUBSYS=${SUBSYS:-eideticom-sc17}
DEV=${DEV:-/dev/nvme0}
PORT=${PORT:-4420}
IP=${IP:-172.18.1.1}

if [ "$(mountpoint $CFG)" != "$CFG is a mountpoint" ]; then
    mount -t configfs none $CFG
fi

cd $CFG/nvmet

mkdir subsystems/$SUBSYS
cd subsystems/$SUBSYS
echo 1 > attr_allow_any_host

i=1
for ns in ${DEV}n*; do
    echo $ns
    mkdir namespaces/$i
    cd namespaces/$i
    echo -n $ns > device_path
    echo 1 > enable
    ((i++))
    cd ../../
done;

cd $CFG/nvmet

mkdir ports/1
cd ports/1
echo -n ipv4 > addr_adrfam
echo -n rdma > addr_trtype
echo -n $PORT > addr_trsvcid
echo -n $IP > addr_traddr

ln -s $CFG/nvmet/subsystems/$SUBSYS \
   $CFG/nvmet/ports/1/subsystems/$SUBSYS
