#!/bin/bash

CFG=${CFG:-/sys/kernel/config/nvmet/}
SUBSYS=${SUBSYS:-eideticom}
PORT=${PORT:-4420}

if [ -e $CFG/subsystems/$SUBSYS/namespaces/1/enable ]; then
    rm -f $CFG/ports/${PORT}/subsystems/$SUBSYS || true
    echo 0 > $CFG/subsystems/$SUBSYS/namespaces/1/enable

    rmdir $CFG/subsystems/$SUBSYS/namespaces/* || true
    rmdir $CFG/subsystems/$SUBSYS || true
    rmdir $CFG/ports/${PORT} || true
fi
