#!/bin/bash

function print {
    echo -n "$1 : tx_bytes :"
    cat /sys/class/infiniband/${1}/ports/1/hw_counters/tx_bytes
    echo -n "$1 : rx_bytes :"
    cat /sys/class/infiniband/${1}/ports/1/hw_counters/rx_bytes
}

print bnxt_re0                                                                                                                          │
print bnxt_re2
