#!/bin/bash
#
# (c) Stephen Bates <stephen@eideticom>, 2017
#
# A simple bash script based on one from Parav Pandit at Mellanox that
# *should* enable loopback via rdma_cm. See [1] for a discussion of
# origin.
#
# [1] https://marc.info/?l=linux-rdma&m=150575871330293&w=2

IFACE0=${IFACE0:-mlx0p1}
IFACE1=${IFACE1:-mlx1p1}
LOOP_10=${LOOP_10:-10}
LOOP_01=${LOOP_01:-20}
IP0=${IP0:-172.18.1.1}
IP1=${IP1:-172.18.11.1}

  # Shift local rules policy to lower priority

ip rule add pref 20 lookup local
ip rule del pref 0

ip rule add pref 1 iif $IFACE0 lookup local
ip rule add pref 2 iif $IFACE1 lookup local

  # Force packet to go out on interface

ip route add default dev $IFACE1 table $LOOP_10 src $IP1
ip route add default dev $IFACE0 table $LOOP_01 src $IP0

 # Define special packets of p0 to p1, p1 to p0 to divert to force
 # table

ip rule add pref 3 to $IP0 lookup $LOOP_10
ip rule add pref 4 to $IP1 lookup $LOOP_01
