#!/bin/bash
#
# Simple wrapper for nvme discover command. Probably needs to be run
# as root. Use IPH to bind to a local interface if needed.

IPH=${IPH:-none}
IPT=${IPT:-172.18.1.1}
NAMESPACE=${NAMESPACE:-eideticom}
TRANS=${TRANS:-rdma}
PORT=${PORT:-4420}

if [ $IPH != "none" ]; then
    nvme connect -t ${TRANS} -a $IPT -w $IPH -n $NAMESPACE -s ${PORT}
else
    nvme connect -t ${TRANS} -a $IPT -n $NAMESPACE -s ${PORT}
fi
