#!/bin/bash
#
# Simple wrapper for nvme discover command. Probably needs to be run
# as root. Use IPH to bind to a local interface if needed.

IPH=${IPH:-none}
IPT=${IPT:-172.18.1.1}
NAMESPACE=${NAMESPACE:-eideticom}

if [ $IPH != "none" ]; then
    nvme connect -t rdma -a $IPT -n $NAMESPACE
else
    nvme connect -t rdma -a $IPT -w $IPH -n $NAMESPACE
fi
